-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 21:19:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema car_wash
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `car_wash` ;

-- -----------------------------------------------------
-- Schema car_wash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_wash` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `car_wash` ;

-- -----------------------------------------------------
-- Table `automoviles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `automoviles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `automoviles` (
  `id_automovil` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `decripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_automovil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `placa_UNIQUE` ON `automoviles` (`placa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `boletas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boletas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `boletas` (
  `id_boleta` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_boleta` VARCHAR(45) NOT NULL,
  `fecha_create` DATETIME NULL DEFAULT NULL,
  `fecha_update` DATETIME NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `id_proforma` INT(11) NOT NULL,
  PRIMARY KEY (`id_boleta`, `id_proforma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `codigo_boleta_UNIQUE` ON `boletas` (`codigo_boleta` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proformas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proformas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proformas` (
  `id_proforma` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_proforma` VARCHAR(100) NOT NULL,
  `fecha_create` DATETIME NULL DEFAULT NULL,
  `update_create` DATETIME NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_proforma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `codigo_proforma_UNIQUE` ON `proformas` (`codigo_proforma` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proformas_automoviles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proformas_automoviles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proformas_automoviles` (
  `proformas_id_proforma` INT(11) NOT NULL,
  `automoviles_id_automovil` INT(11) NOT NULL,
  `fecha_create` DATETIME NULL,
  PRIMARY KEY (`proformas_id_proforma`, `automoviles_id_automovil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  `fecha_create` DATETIME NULL DEFAULT NULL,
  `fecha_update` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servicios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `servicios` (
  `id_servicio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_create` DATETIME NULL DEFAULT NULL,
  `fecha_update` DATETIME NULL DEFAULT NULL,
  `costo` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `servicios_proformas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servicios_proformas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `servicios_proformas` (
  `servicios_id_servicio` INT(11) NOT NULL,
  `proformas_id_proforma` INT(11) NOT NULL,
  `fecha_create` DATETIME NULL,
  PRIMARY KEY (`servicios_id_servicio`, `proformas_id_proforma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apepat` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `token` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_recuperacion` VARCHAR(6) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_create` DATETIME NULL DEFAULT NULL,
  `fecha_update` DATETIME NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `usuarios` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `usuarios` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios_automoviles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios_automoviles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios_automoviles` (
  `usuarios_id_usuario` INT(11) NOT NULL,
  `usuarios_id_rol` INT(11) NOT NULL,
  `automoviles_id_automovil` INT(11) NOT NULL,
  `fecha_create` DATETIME NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `usuarios_id_rol`, `automoviles_id_automovil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios_proformas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios_proformas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios_proformas` (
  `usuarios_id_usuario` INT(11) NOT NULL,
  `usuarios_id_rol` INT(11) NOT NULL,
  `proformas_id_proforma` INT(11) NOT NULL,
  `fecha_create` DATETIME NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `usuarios_id_rol`, `proformas_id_proforma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
